Solution to Code: PRIME1
larissalages/code_problems pull request #168
Opened 2020-10-13 06:25 UTC by kartikeysingh6

Link to the problem!

https://www.codechef.com/problems/PRIME1/

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/larissalages/code_problems/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure your files are in the right folder!
- [x] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [x] If your code is a solution for a code problem, please tell which one.
- [x] Make sure your code is working, test for a lot of cases.

### Description
Please describe your pull request.

:heart: Thank you!

2020-10-13 16:01 UTC, larissalages requested changes
Could you include the .cpp extension in the file? thanks!

2020-10-13 16:32 UTC, kartikeysingh6 commented
> Could you include the .cpp extension in the file? thanks!

How do I change the filename ?

2020-10-14 04:04 UTC, kartikeysingh6 reviewed
added .cpp extension

2020-10-19 02:09 UTC, larissalages approved these changes

2020-10-19 02:09 UTC, merged