Added cpp solution for 238
larissalages/code_problems pull request #200
Opened 2020-10-16 13:40 UTC by shruthi019

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/larissalages/code_problems/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure your files are in the right folder!
- [x] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [x] If your code is a solution for a code problem, please tell which one.
- [x] Make sure your code is working, test for a lot of cases.

### Description
I added the solution in C++ for problem 238 (Product of Array Except Self) in LeetCode.

:heart: Thank you!

2020-10-17 03:46 UTC, larissalages approved these changes

2020-10-17 03:47 UTC, larissalages requested changes
Can you solve the conflicts with master? thanks!

2020-10-17 04:09 UTC, shruthi019 commented
Hey, I saw that a solution was already added for this problem, hence there was a conflict. I cleaned the code and made it more readable, and corrected a typo.

2020-10-19 02:16 UTC, larissalages approved these changes

2020-10-19 02:16 UTC, merged