Added a java program of Hackerank please move it to java folder
larissalages/code_problems pull request #215
Opened 2020-10-16 18:00 UTC by sakshii2695

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/larissalages/code_problems/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure your files are in the right folder!
- [ ] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [ ] If your code is a solution for a code problem, please tell which one.
- [ ] Make sure your code is working, test for a lot of cases.

### Description
Please describe your pull request.

:heart: Thank you!

2020-10-17 15:23 UTC, larissalages requested changes
Could you create a folder named java inside Hackerrank and remove the space on file name? thanks!

2020-10-18 04:44 UTC, sakshii2695 commented
> Could you create a folder named java inside Hackerrank and remove the space on file name? thanks!

done!!

2020-10-18 04:45 UTC, sakshii2695 commented
#215 have made the required changes

2020-10-19 02:19 UTC, larissalages approved these changes

2020-10-19 02:19 UTC, merged