Java-30 days of code solutions added
larissalages/code_problems pull request #273
Opened 2020-10-19 08:06 UTC by sakshi-kst

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/larissalages/code_problems/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure your files are in the right folder!
- [ ] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [ ] If your code is a solution for a code problem, please tell which one.
- [ ] Make sure your code is working, test for a lot of cases.

### Description
Java-30 Days of Code: solutions added for the following problems ->
1. Day 26- Nested Logic
2. Day 27- Testing
3. Day 28- Regex, Patterns, and Intro to Databases
4. Day 29- Bitwise AND

:heart: Thank you!

2020-10-22 02:10 UTC, larissalages approved these changes

2020-10-22 02:11 UTC, larissalages requested changes
Can you put the files inside the java folder? (still inside hackerrank)

2020-10-23 10:15 UTC, sakshi-kst commented
> Can you put the files inside the java folder? (still inside hackerrank)

Added 30 days of code inside Hackerrank -> Java

2020-10-24 21:35 UTC, larissalages approved these changes

2020-10-24 21:36 UTC, merged