Create 206.cpp
larissalages/code_problems pull request #279
Opened 2020-10-20 09:44 UTC by SouravCodery

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/larissalages/code_problems/blob/master/CONTRIBUTING.md) to this repository.

- [ Done] Make sure your files are in the right folder!
- [Done ] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [Done ] If your code is a solution for a code problem, please tell which one.
- [Done] Make sure your code is working, test for a lot of cases.

### Description
Please describe your pull request.

We have implemented the LeetCode's "206 Reverse Linked List" Problem. The solution is well commented and has been accepted by LeetCode's Judge.

Link to the problem: https://leetcode.com/problems/reverse-linked-list/

:heart: Thank you!

2020-10-22 02:19 UTC, larissalages approved these changes

2020-10-22 02:20 UTC, larissalages requested changes
can you solve the conflicts with this file on master? thanks!

2020-10-22 03:21 UTC, SouravCodery commented
> can you solve the conflicts with this file on master? thanks!

Ma'am, The Previous Solution was Iterative while the current one was Recursive. I have kept both the approaches while commenting one of them and have put a comment for people's understanding of the same.

2020-10-22 03:26 UTC, SouravCodery reviewed
The Problem can be solved both iteratively and recursively. Iterative solution was already present, we have added recursive solution now and kept both of them.

2020-10-24 21:28 UTC, larissalages approved these changes

2020-10-24 21:28 UTC, merged